### ISSUE TITLE
npm install 安装依赖包 报错 ，升级最新npm 版本 也报错，不知道怎么回事

### ISSUE THREAD

**Issue by mryangsen** [newbee-ltd/newbee-mall-vue3-app#10]
INFO  Starting development server...
 ERROR  Error: Cannot find module 'vue-loader-v16/package.json'
Require stack:
........
Error: Cannot find module 'vue-loader-v16/package.json'
Require stack:
.....
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newbee-mall-vue3-app@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the newbee-mall-vue3-app@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Edison_\AppData\Roaming\npm-cache\_logs\2020-11-10T03_21_27_855Z-debug.log

**Comment by llllllllllx** [comment]
```
npm i -D vue-loader-v16
```

**Comment by mryangsen** [comment]
重新删除依赖 安装依赖 安装vue-loader-v16 试了三次，没成功&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "newbee-ltd/newbee-mall-vue3-app"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 下午2:57
收件人:&nbsp;"newbee-ltd/newbee-mall-vue3-app"<newbee-mall-vue3-app@noreply.github.com&gt;;
抄送:&nbsp;"Yang."<1831095219@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [newbee-ltd/newbee-mall-vue3-app] npm install 安装依赖包 报错 ，升级最新npm 版本 也报错，不知道怎么回事 (#10)





 npm i -D vue-loader-v16

**Comment by Nick930826** [comment]
@mryangsen 我本地 Node 版本是 v12.6.0，npm 版本是 6.9.0。你的版本是否过高，我之前遇到过版本在 14 以上的安装 npm 包会有问题

**Comment by Nick930826** [comment]
@mryangsen 遇到新蜂商城，下载安装包报错的情况，解决方案如下：
npm cache clean —force 清理一下
删除 package-lock.json 再重新尝试一下
尽量别用 cnpm
