### ISSUE TITLE
demo 里面含大量es6语法，低版本无法正常浏览

### ISSUE THREAD

**Issue by weianzi** [newbee-ltd/newbee-mall-vue3-app#15]
http://47.99.134.126:5008/#/home

**Comment by melunar** [comment]
> http://47.99.134.126:5008/#/home
大哥 这不是demo的问题 es6 已经普及了

**Comment by Nick930826** [comment]
你好，本项目属于手机打开的H5项目，所以手机浏览器已经基本上支持 ES6 的大多数写法。

**Comment by hfyydd** [comment]
部署后 手机端浏览器获取不到后台数据 PC可以 请教是怎么回事

**Comment by Nick930826** [comment]
@hfyydd 请问是什么手机，正常网络请求不分手机还是PC，你看看切到 4g 网络试试。
