### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by qyhf** [newbee-ltd/newbee-mall-vue3-app#16]
postcss-pxtorem能适配华为mate30吗,之前使用px2rem不能适配华为mate30

**Comment by Nick930826** [comment]
@qyhf 适配问题和是否使用 postcss-pxtorem 或 px2rem 无关，它们的作用很明确，把项目中的 px 单位转化为 rem 单位。你想看看是否适配的话，可以用华为meta30打开新蜂商城的线上地址 http://47.99.134.126:5008，看看是否正常就知道了。
