### ISSUE TITLE
所有接口报错

### ISSUE THREAD

**Issue by Cwolf-spirit** [newbee-ltd/newbee-mall-vue3-app#17]
是过年期间服务器关了吗？

**Comment by Nick930826** [comment]
是服务器挂了，尽快修复哈。



---原始邮件---
发件人: "HLL1029"<notifications@github.com&gt;
发送时间: 2021年2月7日(周日) 上午8:57
收件人: "newbee-ltd/newbee-mall-vue3-app"<newbee-mall-vue3-app@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [newbee-ltd/newbee-mall-vue3-app] 所有接口报错 (#17)




 
是过年期间服务器关了吗？

**Comment by newbee-mall** [comment]
小事儿。
