### ISSUE TITLE
关于验证码的问题

### ISSUE THREAD

**Issue by kexiaomeng** [newbee-ltd/newbee-mall-vue3-app#18]
请问大佬，验证码是为了防止恶意行为设计的，但是此项目中验证码是在前台生成的，那不就是只能骗骗正常用户，对恶意行为没有意义了吗？ 恶意行为可以绕过前端验证码直接向后台发送批量的请求进行用户名密码的破解？

**Comment by newbee-mall** [comment]
感谢你的建议！

我不是大佬哈，由于这个开源项目的开发时间不长，所以难免会存在一些小问题。

验证码后面会再改一版的，开源项目都是要慢慢优化的。
