### ISSUE TITLE
大佬，有登录账户密码么

### ISSUE THREAD

**Issue by crydear** [newbee-ltd/newbee-mall-vue3-app#2]

**Comment by newbee-mall** [comment]
在页面上自己注册就可以了呀，提供了注册功能的。

**Comment by MightK** [comment]
爱您~！🤟




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "newbee-ltd/newbee-mall-vue3-app"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 上午9:45
收件人:&nbsp;"newbee-ltd/newbee-mall-vue3-app"<newbee-mall-vue3-app@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [newbee-ltd/newbee-mall-vue3-app] 大佬，有登录账户密码么 (#2)





 
在页面上自己注册就可以了呀，提供了注册功能的。

**Comment by Fun005** [comment]
> 在页面上自己注册就可以了呀，提供了注册功能的。

注册的时候报“请输入正确的手机号！”，但是注册界面没有手机号元素呀

**Comment by JinLai951017** [comment]
注册接口一直报“请输入正确的手机号！”,接口有点问题吧

**Comment by hanmu-bruce** [comment]
垃圾项目来着的
