### ISSUE TITLE
注册 用户名输入非手机号会报错

### ISSUE THREAD

**Issue by haohao594** [newbee-ltd/newbee-mall-vue3-app#20]
![image](https://user-images.githubusercontent.com/42285859/109586439-2ee7d200-7b40-11eb-9e83-07db5a260c10.png)
注册账号的时候接口提示请输入正确手机号，页面中看不出用户名一定要是手机号，用户体验可能会不太好哈哈

**Comment by Nick930826** [comment]
> ![image](https://user-images.githubusercontent.com/42285859/109586439-2ee7d200-7b40-11eb-9e83-07db5a260c10.png)
> 注册账号的时候接口提示请输入正确手机号，页面中看不出用户名一定要是手机号，用户体验可能会不太好哈哈

嗯嗯，表单错误提示需要做一下
