### ISSUE TITLE
适配PC浏览器的 前端？

### ISSUE THREAD

**Issue by ysun** [newbee-ltd/newbee-mall-vue3-app#27]
花一天时间项目跑起来了，后端api+vue3_admin+vue3_app / vue2_app。体验还不错。
但我发现，不管是vue2 还是 vue3版本的用户侧前端UI，好像都是for 移动端设计的。
想问下，我看项目readme里面那个适配PC前端的截图，现在还支持吗？ 那个是mall-plus的UI？
newbee-mall-plus 和 前后端分离的版本，数据库结构一样不，可以使用同一个数据库不？
Thanks

**Comment by ZHENFENG13** [comment]
pc端是newbee-mall仓库里的内容，前端技术栈不是Vue

**Comment by ysun** [comment]
数据库两个项目可以通用的吗？

**Comment by ysun** [comment]
话说，issue的状态，能否等问题解决，或者超时之后，再关闭也不迟啊~~~
