### ISSUE TITLE
由我来提第一个issue的bug

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [newbee-ltd/newbee-mall-vue3-app#3]
问题类型？

bug

bug的发现地？

`product-list`页面

出现什么bug?

重复加载了列表

bug复现行为？

快速刷新

![image](https://user-images.githubusercontent.com/30209304/98491770-de86f480-2270-11eb-9f52-192644572b53.png)

**Comment by xiaoxiaodemeng** [comment]
快速按下搜索按钮也可复现 哦

**Comment by newbee-mall** [comment]
收到！感谢你的反馈。

**Comment by xiaoxiaodemeng** [comment]
> 收到！感谢你的反馈。
首页可以优化一下体验，存在一瞬间只显示几个标题的，然后一瞬间商品出现，有点突兀

**Comment by newbee-mall** [comment]
这个网络问题，服务器带宽是1m的
