### ISSUE TITLE
首页左上角菜单图标的代码在哪？

### ISSUE THREAD

**Issue by zanetti4** [newbee-ltd/newbee-mall-vue3-app#31]
前辈你好！我正在学习 vue 3，克隆了你的前端代码，正在学习。  
首页左上角菜单图标的代码写在哪儿了？通过浏览我猜测你用的是 vant Icon 自定义图标，但是在代码中没有找到使用 *@font-face* 引入第三方或自定义的字体图标样式。能帮我解答一下吗？

**Comment by ZHENFENG13** [comment]
![image](https://user-images.githubusercontent.com/10935614/141926269-64903ae8-c7a0-42fa-8035-f02d5df9b4d3.png)

如上图所示，全局引入了iconfont的字体图标库。

**Comment by zanetti4** [comment]
非常感谢！明白了
