### ISSUE TITLE
登录后底部标签栏中的购物车没有显示商品数徽标

### ISSUE THREAD

**Issue by zanetti4** [newbee-ltd/newbee-mall-vue3-app#33]
在首页点击右上角的登录，在登录页登录成功后跳转回首页，此时底部标签栏的购物车没有立即显示**商品数**徽标，我的购物车内是有商品的，必须点击标签栏进行切换，才能显示出来。

**Comment by ZHENFENG13** [comment]
收到。

**Comment by Nick930826** [comment]
@zanetti4 已修复。

**Comment by zanetti4** [comment]
> @zanetti4 已修复。

看到效果了，赞！
