### ISSUE TITLE
注册账号不成功，无法进一步体验项目

### ISSUE THREAD

**Issue by xiongxiaoshuang** [newbee-ltd/newbee-mall-vue3-app#38]
注册时，提示‘请输入正确的手机号’？？

**Comment by 34455** [comment]
注册是 提示 请输入正确手机号

**Comment by 34455** [comment]
注册时 提示 请输入正确手机号

**Comment by ZHENFENG13** [comment]
随便输入一个手机号格式的账号即可。

![image](https://user-images.githubusercontent.com/10935614/161261036-07b93dc8-04cc-44c9-be88-1c7bf08224da.png)
