### ISSUE TITLE
home 页的header 的显示问题

### ISSUE THREAD

**Issue by lwx1344536674** [newbee-ltd/newbee-mall-vue3-app#39]
home首页的headr 会根据滚动条，控制透明，但是感觉只是将背景透明。文字及内容会显示，建议使用v-show 直接根据滚动隐藏与显示header组件，或v-if

**Comment by ZHENFENG13** [comment]
要的就是这种半透明的效果
![image](https://user-images.githubusercontent.com/10935614/168775905-c2a16a0e-2563-43aa-81a5-5eafa7cfeb92.png)
你可以自行修改哈

**Comment by lwx1344536674** [comment]
好的，






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "newbee-ltd/newbee-mall-vue3-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [newbee-ltd/newbee-mall-vue3-app] home 页的header 的显示问题 (Issue #39)





 
要的就是这种半透明的效果
 
 你可以自行修改哈
