### ISSUE TITLE
注册程序有问题

### ISSUE THREAD

**Issue by createhappymemoryforlife** [newbee-ltd/newbee-mall-vue3-app#45]
默认的账号密码登录不进去，提示请输入正确的手机号，能解决下吗

**Comment by Nick930826** [comment]
重新注册一个号，写11位手机号，不用真实的手机



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月8日(周三) 晚上7:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [newbee-ltd/newbee-mall-vue3-app] 注册程序有问题 (Issue #45)




 
默认的账号密码登录不进去，提示请输入正确的手机号，能解决下吗
