### ISSUE TITLE
请教项目如何处理异常请求的？

### ISSUE THREAD

**Issue by VampireZy** [newbee-ltd/newbee-mall-vue3-app#46]
首先感谢大佬的项目，特别是提供了可以直接访问的服务，方便我这种前端开发直接练手。
不过我看axios的response拦截器，其实，还是有可能走到return Promise.reject(res.data)，但是似乎后续都没有对异常进行处理哇？

**Comment by ZHENFENG13** [comment]
.catch 是捕获reject的方法
