### ISSUE TITLE
本地开发模式下调接口出错

### ISSUE THREAD

**Issue by whatsname66666** [newbee-ltd/newbee-mall-vue3-app#50]
![image](https://user-images.githubusercontent.com/132812455/236673340-fbb05d3b-5123-467a-bb17-c06673e34062.png)
![image](https://user-images.githubusercontent.com/132812455/236673395-54d86e5c-8b68-48bb-9348-a2ef324ae65e.png)

**Comment by ZHENFENG13** [comment]
服务器挂掉了，已处理，你再试一下。
