### ISSUE TITLE
接口文档

### ISSUE THREAD

**Issue by 2234828488** [newbee-ltd/newbee-mall-vue3-app#54]
这个接口文档链接在哪里呀？

**Comment by nknkn-ak** [comment]
同问

**Comment by xliamh** [comment]
稳定安全，免费vpn, 支持chatgpt(https://monkeyff02.online/#/portal?c=ad01)

**Comment by ZHENFENG13** [comment]
https://backend-api-01.newbee.ltd/swagger-ui.html
