### ISSUE TITLE
注册不了

### ISSUE THREAD

**Issue by SoulProgrammerTao** [newbee-ltd/newbee-mall-vue3-app#6]
提示输入正确的手机号

**Comment by newbee-mall** [comment]
你输入一个手机号就可以了

**Comment by SoulProgrammerTao** [comment]
1.没有手机号输入框
2.我在调用注册接口时传入一个手机号依然提示请输入正确的手机号

**Comment by newbee-mall** [comment]
2020-11-09日项目开源当天，到18:00为止，共有211个注册的新用户，图片如下，所以不存在无法注册的情况。
![image](https://user-images.githubusercontent.com/54432435/98527640-37c54700-22b6-11eb-9d31-8bbb2fae9d5f.png)
