### ISSUE TITLE
🐱‍🏍🐱‍🏍🐱‍🏍真诚邀请您使用alova

### ISSUE THREAD

**Issue by JOU-amjs** [newbee-ltd/newbee-mall-vue3-app#60]
您好，我是alovajs的作者胡镇。

仔细看了您写的newbee-mall-vue3-app非常不错，然后我发现项目中使用的是axios，使用方式还较为传统，所以尝试邀请您使用alova+axios，我们也会在alova官网推荐您的项目，不知道您有没兴趣，我简单介绍一下。

[alova文档](https://alova.js.org)

alova定位为下一代请求工具，它的场景化请求策略和更先进的openAPI方案，可以极致简化您项目的api调用，具体推荐您看下[alova简介](https://alova.js.org/tutorial/getting-started/introduce)，您的收益和成本大概是这样的：

收益：alova提供了15+个场景化的请求策略，以及响应缓存和请求共享等高级特性，电商系统有很多列表、表单和商品订单信息，alova的分页策略和表单提交策略都可以让你的项目使用者快速实现完整的列表和表单功能，同时内存缓存还能加快访问速度，配合openAPI还可以获得极致的API集成效率。
成本：我仔细看过newbee-mall-vue3-app源码，可以通过重写`utils/axios.js`模块快速迁移，把导出项改成返回alova实例即可，调用那边与现在保持一致就可以，什么都不用动，因为alova的传参和axios保持了一致，然后也然后是100%适配axios的，你可以用到axios的所有功能。

这些应该会让您的项目增添一点色彩，要是有意向迁移的话，我会提供全力的支持，不知道您意下如何？可以随时通过微信号“alova_js”联系我哦！

**Comment by ZHENFENG13** [comment]
感谢您的关注和欣赏，只不过暂时没时间维护开源仓库了
